# Generated by Django 4.2.5 on 2023-09-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_extracteddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
