# Generated by Django 4.2.5 on 2023-09-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_audioupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='textupload',
            name='predictive_text',
            field=models.TextField(null=True),
        ),
    ]
