# Generated by Django 4.2.5 on 2023-09-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_textupload_predictive_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textupload',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
