# Generated by Django 4.2.5 on 2023-09-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_textupload_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textupload',
            name='predictive_text',
        ),
    ]
